#include "ege.h"

using namespace ege;

#define EGE_EXPECT_OVERLOAD(return_type, name, parameters)                 \
    do {                                                                   \
        typedef return_type (EGE_CDECL *signature_type) parameters;        \
        signature_type selected = static_cast<signature_type>(&ege::name); \
        (void)selected;                                                    \
    } while (false)

int main()
{
    EGE_EXPECT_OVERLOAD(MOUSEMSG, GetMouseMsg, ());
    EGE_EXPECT_OVERLOAD(int, SetCloseHandler, (LPCALLBACK_PROC));
    EGE_EXPECT_OVERLOAD(color_t, alphablend, (color_t, color_t));
    EGE_EXPECT_OVERLOAD(color_t, alphablend, (color_t, color_t, unsigned char));
    EGE_EXPECT_OVERLOAD(color_t, alphablend_premultiplied, (color_t, color_t));
    EGE_EXPECT_OVERLOAD(color_t, alphablend_premultiplied, (color_t, color_t, unsigned char));
    EGE_EXPECT_OVERLOAD(void, api_sleep, (long));
    EGE_EXPECT_OVERLOAD(void, arc, (int, int, int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, arcf, (float, float, float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(int, attachHWND, (HWND));
    EGE_EXPECT_OVERLOAD(void, bar, (int, int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, bar3d, (int, int, int, int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, circle, (int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, circlef, (float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(bool, clear_console, ());
    EGE_EXPECT_OVERLOAD(void, cleardevice, (PIMAGE));
    EGE_EXPECT_OVERLOAD(void, clearviewport, (PIMAGE));
    EGE_EXPECT_OVERLOAD(bool, close_console, ());
    EGE_EXPECT_OVERLOAD(void, closegraph, ());
    EGE_EXPECT_OVERLOAD(color_t, color_premultiply, (color_t));
    EGE_EXPECT_OVERLOAD(color_t, color_unpremultiply, (color_t));
    EGE_EXPECT_OVERLOAD(color_t, colorblend, (color_t, color_t, unsigned char));
    EGE_EXPECT_OVERLOAD(color_t, colorblend_f, (color_t, color_t, unsigned char));
    EGE_EXPECT_OVERLOAD(void, delay, (long));
    EGE_EXPECT_OVERLOAD(void, delay_fps, (double));
    EGE_EXPECT_OVERLOAD(void, delay_fps, (int));
    EGE_EXPECT_OVERLOAD(void, delay_fps, (long));
    EGE_EXPECT_OVERLOAD(void, delay_jfps, (double));
    EGE_EXPECT_OVERLOAD(void, delay_jfps, (int));
    EGE_EXPECT_OVERLOAD(void, delay_jfps, (long));
    EGE_EXPECT_OVERLOAD(void, delay_ms, (long));
    EGE_EXPECT_OVERLOAD(void, delimage, (PCIMAGE));
    EGE_EXPECT_OVERLOAD(void, drawbezier, (int, const int*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, drawlines, (int, const int*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, drawpoly, (int, const int*, PIMAGE));
#ifdef EGE_GDIPLUS
    EGE_EXPECT_OVERLOAD(void, ege_arc, (float, float, float, float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_bezier, (int, const ege_point*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_circle, (float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(int, ege_compress, (void*, uint32_t*, const void*, uint32_t));
    EGE_EXPECT_OVERLOAD(int, ege_compress2, (void*, uint32_t*, const void*, uint32_t, int));
    EGE_EXPECT_OVERLOAD(uint32_t, ege_compress_bound, (uint32_t));
    EGE_EXPECT_OVERLOAD(void, ege_drawbezier, (int, const ege_point*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_drawclosedcurve, (int, const ege_point*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_drawclosedcurve, (int, const ege_point*, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_drawcurve, (int, const ege_point*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_drawcurve, (int, const ege_point*, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_drawimage, (PCIMAGE, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_drawimage, (PCIMAGE, int, int, int, int, int, int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_drawpath, (const ege_path*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_drawpath, (const ege_path*, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_drawpoly, (int, const ege_point*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_drawtext, (const char*, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_drawtext, (const wchar_t*, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_ellipse, (float, float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_enable_aa, (bool, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_fillcircle, (float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_fillclosedcurve, (int, const ege_point*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_fillclosedcurve, (int, const ege_point*, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_fillellipse, (float, float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_fillpath, (const ege_path*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_fillpath, (const ege_path*, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_fillpie, (float, float, float, float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_fillpoly, (int, const ege_point*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_fillrect, (float, float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_fillroundrect, (float, float, float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_fillroundrect, (float, float, float, float, float, float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_gentexture, (bool, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_get_transform, (ege_transform_matrix*, PIMAGE));
    EGE_EXPECT_OVERLOAD(int, ege_getch, ());
    EGE_EXPECT_OVERLOAD(int, ege_kbhit, ());
    EGE_EXPECT_OVERLOAD(void, ege_line, (float, float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_outtextxy, (float, float, char, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_outtextxy, (float, float, const char*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_outtextxy, (float, float, const wchar_t*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_outtextxy, (float, float, wchar_t, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_path_addarc, (ege_path*, float, float, float, float, float, float));
    EGE_EXPECT_OVERLOAD(void, ege_path_addbezier, (ege_path*, float, float, float, float, float, float, float, float));
    EGE_EXPECT_OVERLOAD(void, ege_path_addbezier, (ege_path*, int, const ege_point*));
    EGE_EXPECT_OVERLOAD(void, ege_path_addcircle, (ege_path*, float, float, float));
    EGE_EXPECT_OVERLOAD(void, ege_path_addclosedcurve, (ege_path*, int, const ege_point*));
    EGE_EXPECT_OVERLOAD(void, ege_path_addclosedcurve, (ege_path*, int, const ege_point*, float));
    EGE_EXPECT_OVERLOAD(void, ege_path_addcurve, (ege_path*, int, const ege_point*));
    EGE_EXPECT_OVERLOAD(void, ege_path_addcurve, (ege_path*, int, const ege_point*, float));
    EGE_EXPECT_OVERLOAD(void, ege_path_addellipse, (ege_path*, float, float, float, float));
    EGE_EXPECT_OVERLOAD(void, ege_path_addline, (ege_path*, float, float, float, float));
    EGE_EXPECT_OVERLOAD(void, ege_path_addpath, (ege_path*, const ege_path*, bool));
    EGE_EXPECT_OVERLOAD(void, ege_path_addpie, (ege_path*, float, float, float, float, float, float));
    EGE_EXPECT_OVERLOAD(void, ege_path_addpolygon, (ege_path*, int, const ege_point*));
    EGE_EXPECT_OVERLOAD(void, ege_path_addpolyline, (ege_path*, int, const ege_point*));
    EGE_EXPECT_OVERLOAD(void, ege_path_addrect, (ege_path*, float, float, float, float));
    EGE_EXPECT_OVERLOAD(void, ege_path_addtext, (ege_path*, float, float, const char*, float, int, const char*, int));
    EGE_EXPECT_OVERLOAD(void, ege_path_addtext, (ege_path*, float, float, const wchar_t*, float, int, const wchar_t*, int));
    EGE_EXPECT_OVERLOAD(ege_path*, ege_path_clone, (const ege_path*));
    EGE_EXPECT_OVERLOAD(void, ege_path_close, (ege_path*));
    EGE_EXPECT_OVERLOAD(void, ege_path_closeall, (ege_path*));
    EGE_EXPECT_OVERLOAD(ege_path*, ege_path_create, ());
    EGE_EXPECT_OVERLOAD(ege_path*, ege_path_createfrom, (const ege_point*, const unsigned char*, int));
    EGE_EXPECT_OVERLOAD(void, ege_path_destroy, (const ege_path*));
    EGE_EXPECT_OVERLOAD(void, ege_path_flatten, (ege_path*, const ege_transform_matrix*));
    EGE_EXPECT_OVERLOAD(void, ege_path_flatten, (ege_path*, const ege_transform_matrix*, float));
    EGE_EXPECT_OVERLOAD(ege_rect, ege_path_getbounds, (const ege_path*, const ege_transform_matrix*));
    EGE_EXPECT_OVERLOAD(ege_rect, ege_path_getbounds, (const ege_path*, const ege_transform_matrix*, PCIMAGE));
    EGE_EXPECT_OVERLOAD(ege_point*, ege_path_getpathpoints, (const ege_path*, ege_point*));
    EGE_EXPECT_OVERLOAD(unsigned char*, ege_path_getpathtypes, (const ege_path*, unsigned char*));
    EGE_EXPECT_OVERLOAD(bool, ege_path_inpath, (const ege_path*, float, float));
    EGE_EXPECT_OVERLOAD(bool, ege_path_inpath, (const ege_path*, float, float, PCIMAGE));
    EGE_EXPECT_OVERLOAD(bool, ege_path_instroke, (const ege_path*, float, float));
    EGE_EXPECT_OVERLOAD(bool, ege_path_instroke, (const ege_path*, float, float, PCIMAGE));
    EGE_EXPECT_OVERLOAD(ege_point, ege_path_lastpoint, (const ege_path*));
    EGE_EXPECT_OVERLOAD(void, ege_path_outline, (ege_path*, const ege_transform_matrix*));
    EGE_EXPECT_OVERLOAD(void, ege_path_outline, (ege_path*, const ege_transform_matrix*, float));
    EGE_EXPECT_OVERLOAD(int, ege_path_pointcount, (const ege_path*));
    EGE_EXPECT_OVERLOAD(void, ege_path_reset, (ege_path*));
    EGE_EXPECT_OVERLOAD(void, ege_path_reverse, (ege_path*));
    EGE_EXPECT_OVERLOAD(void, ege_path_setfillmode, (ege_path*, fill_mode));
    EGE_EXPECT_OVERLOAD(void, ege_path_start, (ege_path*));
    EGE_EXPECT_OVERLOAD(void, ege_path_transform, (ege_path*, const ege_transform_matrix*));
    EGE_EXPECT_OVERLOAD(void, ege_path_warp, (ege_path*, const ege_point*, int, const ege_rect*, const ege_transform_matrix*));
    EGE_EXPECT_OVERLOAD(void, ege_path_warp, (ege_path*, const ege_point*, int, const ege_rect*, const ege_transform_matrix*, float));
    EGE_EXPECT_OVERLOAD(void, ege_path_widen, (ege_path*, float, const ege_transform_matrix*));
    EGE_EXPECT_OVERLOAD(void, ege_path_widen, (ege_path*, float, const ege_transform_matrix*, float));
    EGE_EXPECT_OVERLOAD(void, ege_pie, (float, float, float, float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_polygon, (int, const ege_point*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_polyline, (int, const ege_point*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_puttexture, (PCIMAGE, ege_rect, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_puttexture, (PCIMAGE, ege_rect, ege_rect, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_puttexture, (PCIMAGE, float, float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_rectangle, (float, float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_roundrect, (float, float, float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_roundrect, (float, float, float, float, float, float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_set_transform, (const ege_transform_matrix*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_setalpha, (int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_setpattern_ellipsegradient, (ege_point, color_t, float, float, float, float, color_t, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_setpattern_lineargradient, (float, float, color_t, float, float, color_t, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_setpattern_none, (PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_setpattern_pathgradient, (ege_point, color_t, int, const ege_point*, int, const color_t*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_setpattern_texture, (PIMAGE, float, float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_sleep, (long));
    EGE_EXPECT_OVERLOAD(ege_point, ege_transform_calc, (ege_point, PIMAGE));
    EGE_EXPECT_OVERLOAD(ege_point, ege_transform_calc, (float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_transform_reset, (PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_transform_rotate, (float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_transform_scale, (float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ege_transform_translate, (float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(int, ege_uncompress, (void*, uint32_t*, const void*, uint32_t));
    EGE_EXPECT_OVERLOAD(uint32_t, ege_uncompress_size, (const void*, uint32_t));
    EGE_EXPECT_OVERLOAD(void, ege_xyprintf, (float, float, const char*, ...));
    EGE_EXPECT_OVERLOAD(void, ege_xyprintf, (float, float, const wchar_t*, ...));
#endif
    EGE_EXPECT_OVERLOAD(void, ellipse, (int, int, int, int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, ellipsef, (float, float, float, float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(double, fclock, ());
    EGE_EXPECT_OVERLOAD(void, fillcircle, (int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, fillcirclef, (float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, fillellipse, (int, int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, fillellipsef, (float, float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, fillpie, (int, int, int, int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, fillpief, (float, float, float, float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, fillpoly, (int, const int*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, fillpoly_gradient, (int, const ege_colpoint*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, fillrect, (int, int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, fillroundrect, (int, int, int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, fillroundrect, (int, int, int, int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, floodfill, (int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, floodfillsurface, (int, int, color_t, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, flushkey, ());
    EGE_EXPECT_OVERLOAD(void, flushmouse, ());
    EGE_EXPECT_OVERLOAD(void, flushwindow, ());
    EGE_EXPECT_OVERLOAD(long, getGraphicsVer, ());
    EGE_EXPECT_OVERLOAD(HDC, getHDC, (PCIMAGE));
    EGE_EXPECT_OVERLOAD(HINSTANCE, getHInstance, ());
    EGE_EXPECT_OVERLOAD(HWND, getHWnd, ());
    EGE_EXPECT_OVERLOAD(PVOID, getProcfunc, ());
    EGE_EXPECT_OVERLOAD(color_t, getbkcolor, (PCIMAGE));
    EGE_EXPECT_OVERLOAD(color_t*, getbuffer, (PIMAGE));
    EGE_EXPECT_OVERLOAD(color_t*, getbuffer, (PIMAGE, image_buffer_access));
    EGE_EXPECT_OVERLOAD(const color_t*, getbuffer, (PCIMAGE));
    EGE_EXPECT_OVERLOAD(int, getch, ());
    EGE_EXPECT_OVERLOAD(int, getchEx, (int));
    EGE_EXPECT_OVERLOAD(int, getch_console, ());
    EGE_EXPECT_OVERLOAD(unsigned int, getcodepage, ());
    EGE_EXPECT_OVERLOAD(color_t, getcolor, (PCIMAGE));
    EGE_EXPECT_OVERLOAD(color_t, getfillcolor, (PCIMAGE));
    EGE_EXPECT_OVERLOAD(void, getfont, (LOGFONTA*, PCIMAGE));
    EGE_EXPECT_OVERLOAD(void, getfont, (LOGFONTW*, PCIMAGE));
    EGE_EXPECT_OVERLOAD(float, getfps, ());
    EGE_EXPECT_OVERLOAD(int, getheight, (PCIMAGE));
    EGE_EXPECT_OVERLOAD(int, getimage, (PIMAGE, PCIMAGE, int, int, int, int));
    EGE_EXPECT_OVERLOAD(int, getimage, (PIMAGE, const char*, const char*, int, int));
    EGE_EXPECT_OVERLOAD(int, getimage, (PIMAGE, const char*, int, int));
    EGE_EXPECT_OVERLOAD(int, getimage, (PIMAGE, const wchar_t*, const wchar_t*, int, int));
    EGE_EXPECT_OVERLOAD(int, getimage, (PIMAGE, const wchar_t*, int, int));
    EGE_EXPECT_OVERLOAD(int, getimage, (PIMAGE, int, int, int, int));
    EGE_EXPECT_OVERLOAD(int, getimage_pngfile, (PIMAGE, const char*));
    EGE_EXPECT_OVERLOAD(int, getimage_pngfile, (PIMAGE, const wchar_t*));
    EGE_EXPECT_OVERLOAD(image_storage_mode, getimagestoragemode, (PCIMAGE));
    EGE_EXPECT_OVERLOAD(initmode_flag, getinitmode, ());
    EGE_EXPECT_OVERLOAD(key_msg, getkey, ());
    EGE_EXPECT_OVERLOAD(line_cap_type, getlinecap, (PCIMAGE));
    EGE_EXPECT_OVERLOAD(void, getlinecap, (line_cap_type*, line_cap_type*, PCIMAGE));
    EGE_EXPECT_OVERLOAD(color_t, getlinecolor, (PCIMAGE));
    EGE_EXPECT_OVERLOAD(line_join_type, getlinejoin, (PCIMAGE));
    EGE_EXPECT_OVERLOAD(void, getlinejoin, (line_join_type*, float*, PCIMAGE));
    EGE_EXPECT_OVERLOAD(void, getlinestyle, (int*, unsigned short*, int*, PCIMAGE));
    EGE_EXPECT_OVERLOAD(mouse_msg, getmouse, ());
    EGE_EXPECT_OVERLOAD(color_t, getpixel, (int, int, PCIMAGE));
    EGE_EXPECT_OVERLOAD(color_t, getpixel_f, (int, int, PCIMAGE));
    EGE_EXPECT_OVERLOAD(color_t, gettextcolor, (PCIMAGE));
    EGE_EXPECT_OVERLOAD(bool, getunicodecharmessage, ());
    EGE_EXPECT_OVERLOAD(void, getviewport, (int*, int*, int*, int*, int*, PCIMAGE));
    EGE_EXPECT_OVERLOAD(int, getwidth, (PCIMAGE));
    EGE_EXPECT_OVERLOAD(int, getx, (PCIMAGE));
    EGE_EXPECT_OVERLOAD(int, gety, (PCIMAGE));
    EGE_EXPECT_OVERLOAD(bool, hide_console, ());
    EGE_EXPECT_OVERLOAD(void, hidewindow, ());
    EGE_EXPECT_OVERLOAD(color_t, hsl2rgb, (float, float, float));
    EGE_EXPECT_OVERLOAD(color_t, hsv2rgb, (float, float, float));
    EGE_EXPECT_OVERLOAD(void, image_convertcolor, (PIMAGE, color_type, color_type));
    EGE_EXPECT_OVERLOAD(int, imagefilter_blurring, (PIMAGE, int, int, int, int, int, int));
    EGE_EXPECT_OVERLOAD(bool, init_console, ());
    EGE_EXPECT_OVERLOAD(void, initgraph, (int, int));
    EGE_EXPECT_OVERLOAD(void, initgraph, (int, int, initmode_flag));
    EGE_EXPECT_OVERLOAD(int, inputbox_getline, (const char*, const char*, LPSTR, int));
    EGE_EXPECT_OVERLOAD(int, inputbox_getline, (const wchar_t*, const wchar_t*, LPWSTR, int));
    EGE_EXPECT_OVERLOAD(bool, is_run, ());
    EGE_EXPECT_OVERLOAD(int, kbhit, ());
    EGE_EXPECT_OVERLOAD(int, kbhitEx, (int));
    EGE_EXPECT_OVERLOAD(int, kbhit_console, ());
    EGE_EXPECT_OVERLOAD(int, kbmsg, ());
    EGE_EXPECT_OVERLOAD(int, keypress, (int));
    EGE_EXPECT_OVERLOAD(int, keyrelease, (int));
    EGE_EXPECT_OVERLOAD(int, keyrepeat, (int));
    EGE_EXPECT_OVERLOAD(bool, keystate, (int));
    EGE_EXPECT_OVERLOAD(void, line, (int, int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, line_f, (float, float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, linerel, (int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, linerel_f, (float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, lineto, (int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, lineto_f, (float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, measuretext, (char, float*, float*, PCIMAGE));
    EGE_EXPECT_OVERLOAD(void, measuretext, (const char*, float*, float*, PCIMAGE));
    EGE_EXPECT_OVERLOAD(void, measuretext, (const wchar_t*, float*, float*, PCIMAGE));
    EGE_EXPECT_OVERLOAD(void, measuretext, (wchar_t, float*, float*, PCIMAGE));
    EGE_EXPECT_OVERLOAD(int, mousemsg, ());
    EGE_EXPECT_OVERLOAD(int, mousepos, (int*, int*));
    EGE_EXPECT_OVERLOAD(void, moverel, (int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, moveto, (int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, movewindow, (int, int, bool));
    EGE_EXPECT_OVERLOAD(PIMAGE, newimage, ());
    EGE_EXPECT_OVERLOAD(PIMAGE, newimage, (int, int));
    EGE_EXPECT_OVERLOAD(void, outtext, (char, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, outtext, (const char*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, outtext, (const wchar_t*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, outtext, (wchar_t, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, outtextrect, (int, int, int, int, const char*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, outtextrect, (int, int, int, int, const wchar_t*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, outtextxy, (int, int, char, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, outtextxy, (int, int, const char*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, outtextxy, (int, int, const wchar_t*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, outtextxy, (int, int, wchar_t, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, pie, (int, int, int, int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, pief, (float, float, float, float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, pieslice, (int, int, int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, pieslicef, (float, float, float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, polygon, (int, const int*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, polyline, (int, const int*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, putimage, (PIMAGE, int, int, PCIMAGE, DWORD));
    EGE_EXPECT_OVERLOAD(void, putimage, (PIMAGE, int, int, int, int, PCIMAGE, int, int, DWORD));
    EGE_EXPECT_OVERLOAD(void, putimage, (PIMAGE, int, int, int, int, PCIMAGE, int, int, int, int, DWORD));
    EGE_EXPECT_OVERLOAD(void, putimage, (int, int, PCIMAGE, DWORD));
    EGE_EXPECT_OVERLOAD(void, putimage, (int, int, int, int, PCIMAGE, int, int, DWORD));
    EGE_EXPECT_OVERLOAD(void, putimage, (int, int, int, int, PCIMAGE, int, int, int, int, DWORD));
    EGE_EXPECT_OVERLOAD(int, putimage_alphablend, (PIMAGE, PCIMAGE, int, int, int, int, unsigned char, int, int, int, int, bool, color_type));
    EGE_EXPECT_OVERLOAD(int, putimage_alphablend, (PIMAGE, PCIMAGE, int, int, unsigned char, color_type));
    EGE_EXPECT_OVERLOAD(int, putimage_alphablend, (PIMAGE, PCIMAGE, int, int, unsigned char, int, int, color_type));
    EGE_EXPECT_OVERLOAD(int, putimage_alphablend, (PIMAGE, PCIMAGE, int, int, unsigned char, int, int, int, int, color_type));
    EGE_EXPECT_OVERLOAD(int, putimage_alphafilter, (PIMAGE, PCIMAGE, int, int, PCIMAGE, int, int, int, int));
    EGE_EXPECT_OVERLOAD(int, putimage_alphatransparent, (PIMAGE, PCIMAGE, int, int, color_t, unsigned char, int, int, int, int));
    EGE_EXPECT_OVERLOAD(int, putimage_rotate, (PIMAGE, PCIMAGE, int, int, float, float, float, bool, int, bool));
    EGE_EXPECT_OVERLOAD(int, putimage_rotatetransparent, (PIMAGE, PCIMAGE, int, int, int, int, color_t, float, float));
    EGE_EXPECT_OVERLOAD(int, putimage_rotatetransparent, (PIMAGE, PCIMAGE, int, int, int, int, int, int, int, int, color_t, float, float));
    EGE_EXPECT_OVERLOAD(int, putimage_rotatezoom, (PIMAGE, PCIMAGE, int, int, float, float, float, float, bool, int, bool));
    EGE_EXPECT_OVERLOAD(int, putimage_transparent, (PIMAGE, PCIMAGE, int, int, color_t, int, int, int, int));
    EGE_EXPECT_OVERLOAD(int, putimage_withalpha, (PIMAGE, PCIMAGE, int, int, int, int, int, int));
    EGE_EXPECT_OVERLOAD(int, putimage_withalpha, (PIMAGE, PCIMAGE, int, int, int, int, int, int, int, int, bool));
    EGE_EXPECT_OVERLOAD(void, putpixel, (int, int, color_t, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, putpixel_alphablend, (int, int, color_t, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, putpixel_alphablend, (int, int, color_t, unsigned char, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, putpixel_alphablend_f, (int, int, color_t, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, putpixel_alphablend_f, (int, int, color_t, unsigned char, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, putpixel_f, (int, int, color_t, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, putpixel_savealpha, (int, int, color_t, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, putpixel_savealpha_f, (int, int, color_t, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, putpixel_withalpha, (int, int, color_t, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, putpixel_withalpha_f, (int, int, color_t, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, putpixels, (int, const int*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, putpixels_f, (int, const int*, PIMAGE));
    EGE_EXPECT_OVERLOAD(unsigned int, random, (unsigned int));
    EGE_EXPECT_OVERLOAD(double, randomf, ());
    EGE_EXPECT_OVERLOAD(unsigned int, randomize, ());
    EGE_EXPECT_OVERLOAD(unsigned int, randomize, (unsigned int));
    EGE_EXPECT_OVERLOAD(void, rectangle, (int, int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, rectprintf, (int, int, int, int, const char*, ...));
    EGE_EXPECT_OVERLOAD(void, rectprintf, (int, int, int, int, const wchar_t*, ...));
    EGE_EXPECT_OVERLOAD(int, resize, (PIMAGE, int, int));
    EGE_EXPECT_OVERLOAD(int, resize_f, (PIMAGE, int, int));
    EGE_EXPECT_OVERLOAD(void, resizewindow, (int, int));
    EGE_EXPECT_OVERLOAD(color_t, rgb2gray, (color_t));
    EGE_EXPECT_OVERLOAD(void, rgb2hsl, (color_t, float*, float*, float*));
    EGE_EXPECT_OVERLOAD(void, rgb2hsv, (color_t, float*, float*, float*));
    EGE_EXPECT_OVERLOAD(void, rotate_point3d_x, (VECTOR3D*, float));
    EGE_EXPECT_OVERLOAD(void, rotate_point3d_y, (VECTOR3D*, float));
    EGE_EXPECT_OVERLOAD(void, rotate_point3d_z, (VECTOR3D*, float));
    EGE_EXPECT_OVERLOAD(void, roundrect, (int, int, int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, roundrect, (int, int, int, int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(int, savebmp, (PCIMAGE, const char*, bool));
    EGE_EXPECT_OVERLOAD(int, savebmp, (PCIMAGE, const wchar_t*, bool));
    EGE_EXPECT_OVERLOAD(int, saveimage, (PCIMAGE, const char*, bool));
    EGE_EXPECT_OVERLOAD(int, saveimage, (PCIMAGE, const wchar_t*, bool));
    EGE_EXPECT_OVERLOAD(int, savepng, (PCIMAGE, const char*, bool));
    EGE_EXPECT_OVERLOAD(int, savepng, (PCIMAGE, const wchar_t*, bool));
    EGE_EXPECT_OVERLOAD(void, sector, (int, int, int, int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, sectorf, (float, float, float, float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, setactivepage, (int));
    EGE_EXPECT_OVERLOAD(void, setbkcolor, (color_t, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, setbkcolor_f, (color_t, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, setbkmode, (int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, setcaption, (const char*));
    EGE_EXPECT_OVERLOAD(void, setcaption, (const wchar_t*));
    EGE_EXPECT_OVERLOAD(void, setcodepage, (unsigned int));
    EGE_EXPECT_OVERLOAD(void, setcolor, (color_t, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, setfillcolor, (color_t, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, setfillstyle, (int, color_t, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, setfont, (const LOGFONTA*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, setfont, (const LOGFONTW*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, setfont, (int, int, const char*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, setfont, (int, int, const char*, int, int, int, bool, bool, bool, BYTE, BYTE, BYTE, BYTE, BYTE, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, setfont, (int, int, const char*, int, int, int, bool, bool, bool, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, setfont, (int, int, const wchar_t*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, setfont, (int, int, const wchar_t*, int, int, int, bool, bool, bool, BYTE, BYTE, BYTE, BYTE, BYTE, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, setfont, (int, int, const wchar_t*, int, int, int, bool, bool, bool, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, setfontbkcolor, (color_t, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, seticon, (int));
    EGE_EXPECT_OVERLOAD(int, setimagestoragemode, (PIMAGE, image_storage_mode));
    EGE_EXPECT_OVERLOAD(void, setinitmode, (initmode_flag, int, int));
    EGE_EXPECT_OVERLOAD(void, setlinecap, (line_cap_type, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, setlinecap, (line_cap_type, line_cap_type, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, setlinecolor, (color_t, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, setlinejoin, (line_join_type, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, setlinejoin, (line_join_type, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, setlinestyle, (int, unsigned short, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, setlinewidth, (float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, setrendermode, (rendermode_e));
    EGE_EXPECT_OVERLOAD(void, settextcolor, (color_t, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, settextjustify, (int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, setunicodecharmessage, (bool));
    EGE_EXPECT_OVERLOAD(void, setviewport, (int, int, int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, setvisualpage, (int));
    EGE_EXPECT_OVERLOAD(void, setwritemode, (int, PIMAGE));
    EGE_EXPECT_OVERLOAD(bool, show_console, ());
    EGE_EXPECT_OVERLOAD(int, showmouse, (int));
    EGE_EXPECT_OVERLOAD(void, showwindow, ());
    EGE_EXPECT_OVERLOAD(void, solidcircle, (int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, solidcirclef, (float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, solidellipse, (int, int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, solidellipsef, (float, float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, solidpie, (int, int, int, int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, solidpief, (float, float, float, float, float, float, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, solidpoly, (int, const int*, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, solidrect, (int, int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, solidroundrect, (int, int, int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, solidroundrect, (int, int, int, int, int, int, PIMAGE));
    EGE_EXPECT_OVERLOAD(void, swappage, ());
    EGE_EXPECT_OVERLOAD(int, textheight, (char, PCIMAGE));
    EGE_EXPECT_OVERLOAD(int, textheight, (const char*, PCIMAGE));
    EGE_EXPECT_OVERLOAD(int, textheight, (const wchar_t*, PCIMAGE));
    EGE_EXPECT_OVERLOAD(int, textheight, (wchar_t, PCIMAGE));
    EGE_EXPECT_OVERLOAD(int, textwidth, (char, PCIMAGE));
    EGE_EXPECT_OVERLOAD(int, textwidth, (const char*, PCIMAGE));
    EGE_EXPECT_OVERLOAD(int, textwidth, (const wchar_t*, PCIMAGE));
    EGE_EXPECT_OVERLOAD(int, textwidth, (wchar_t, PCIMAGE));
    EGE_EXPECT_OVERLOAD(int, updatebuffer, (PIMAGE, int, int, int, int, const color_t*, int));
    EGE_EXPECT_OVERLOAD(void, window_getviewport, (int*, int*, int*, int*));
    EGE_EXPECT_OVERLOAD(void, window_getviewport, (viewporttype*));
    EGE_EXPECT_OVERLOAD(void, window_setviewport, (int, int, int, int));
    EGE_EXPECT_OVERLOAD(void, xyprintf, (int, int, const char*, ...));
    EGE_EXPECT_OVERLOAD(void, xyprintf, (int, int, const wchar_t*, ...));
    return 0;
}

#undef EGE_EXPECT_OVERLOAD
