name: pages build and deployment

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Skip deploy
        run: echo "Deploy step removed"
